export const FORGOT_PASSWORD_REQUEST = "XcelTrip/LoginContainer/FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "XcelTrip/LoginContainer/FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "XcelTrip/LoginContainer/FORGOT_PASSWORD_FAILURE";

export const RESEND_CONFIRMATION_REQUEST = 'XcelTrip/LoginContainer/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'XcelTrip/LoginContainer/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'XcelTrip/LoginContainer/RESEND_CONFIRMATION_FAILURE';

export const RESET_FORGOT_PASSWORD = "XcelTrip/LoginContainer/FORGOT_PASSWORD_RESET";
